repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 18ad293fc9d1852776afe35015a932b68d26fb14
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: (ibis/_version|versioneer).py
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
        types:
          - python
