name: sql_to_ibis
channels:
  - conda-forge
dependencies:
  # required
  - lark=1.1.2
  - ibis-framework=2.1.1

  # Test requirements
  - flake8
  - mypy
  - isort
  - pytest
  - pandas
  - pytest
  - pytest-cov
  - freezegun

  - pip
  - pip:
      - black
